spring:
  application:
    name: demoservice
    cache: 2
server:
  port: 9000

---
spring:
  profiles: dev
  application:
    name: demoservice
    cache: 2
server:
  port: 9090

---
spring:
  profiles: prod
  application:
    name: demoservice
    cache: 2
server:
  port: 4431